//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REMSolution
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertyType
    {
        public PropertyType()
        {
            this.RealProperties = new HashSet<RealProperty>();
        }
    
        public int PropertyTypeId { get; set; }
        public string PropertyTypeName { get; set; }
        public string Icon { get; set; }
    
        public virtual ICollection<RealProperty> RealProperties { get; set; }
    }
}
