//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REMSolution
{
    using System;
    using System.Collections.Generic;
    
    public partial class RealProperty
    {
        public int PropertyID { get; set; }
        public string PropertyName { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public Nullable<int> RecordSourceID { get; set; }
        public Nullable<decimal> ListPrice { get; set; }
        public Nullable<decimal> Zestimate { get; set; }
        public Nullable<int> PropertyTypeId { get; set; }
        public string Garage { get; set; }
        public string Bedrooms { get; set; }
        public string Bathrooms { get; set; }
        public string SquareFeet { get; set; }
        public string Basement { get; set; }
    
        public virtual PropertyType PropertyType { get; set; }
        public virtual RecordSource RecordSource { get; set; }
    }
}
