//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REMSolution
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecordSource
    {
        public RecordSource()
        {
            this.RealProperties = new HashSet<RealProperty>();
        }
    
        public int RecordSourceID { get; set; }
        public string RecordSourceName { get; set; }
    
        public virtual RecordSource RecordSources1 { get; set; }
        public virtual RecordSource RecordSource1 { get; set; }
        public virtual ICollection<RealProperty> RealProperties { get; set; }
    }
}
